# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('leader', models.CharField(max_length=40)),
                ('main_speciality', models.CharField(max_length=40)),
                ('number_of_members', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gift', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Worker'),
        ),
    ]
