# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20161213_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='department',
        ),
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers', to='app1.Department'),
        ),
    ]
