# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good_description',
            fields=[
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.Good')),
            ],
        ),
    ]
